###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

learningsf-memcached:
  image: phpdockerio/memcached:latest
  container_name: learningsf-memcached

learningsf-mysql:
  image: mysql:5.7
  container_name: learningsf-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_DATABASE=db
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass

learningsf-webserver:
  image: phpdockerio/nginx:latest
  container_name: learningsf-webserver
  volumes:
      - .:/var/www/learningsf
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - learningsf-php-fpm

learningsf-php-fpm:
  build: .
  dockerfile: ./phpdocker/php-fpm/Dockerfile
  container_name: learningsf-php-fpm
  volumes:
    - .:/var/www/learningsf
    - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - learningsf-memcached
    - learningsf-mysql
  command: bash -c "cd /var/www/learningsf/ && composer install && chown -R www-data:www-data /var/www/learningsf/vendor && /usr/sbin/php-fpm7.1 -F -O 2>&1"
