imports:
    - { resource: services.yml }
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "12345"
#    router:
#        resource: "%kernel.root_dir%/config/routing.yml"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "pl-PL"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   %kernel.root_dir%/../var/sessions/%kernel.environment%
    fragments:       ~
    http_method_override: true
    assets: ~
    profiler: ~
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/efikuBundle/Resources" : ~
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        dbname:   efikowo
        path:     "%kernel.root_dir%/../var/db.sqlite"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
